--Explore All objects in the database
--Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore all columns in the database
SELECT *FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all categories 'The Major Divisons'
SELECT DISTINCT	category , subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

--Date Exploratiton
-- find the date of the first and lst order
SELECT 
MIN(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(month,MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the youngest and the oldest customer 
SELECT 
MIN(birthdate) oldest_birthdate,
DATEDIFF(year,MIN(birthdate),GETDATE()) AS oLdest_age,
MAX(birthdate) youngest_birtdate,
DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

-- Measures Exploration
-- Find the Total Sales
SELECT 
SUM(sales_amount) as total_sales
FROM gold.fact_sales	 
-- Find how many items are sold
SELECT 
SUM(quantity) as total_squantity
FROM gold.fact_sales
-- find the average selling price
SELECT 
avg(price) as avgprice
FROM gold.fact_sales
-- find the total number of orders
SELECT 
count(order_number) as total_orders
FROM gold.fact_sales

SELECT 
COUNT(DISTINCT order_number) as total_orders
FROM gold.fact_sales

-- find the total number of products
SELECT COUNT(product_key) as total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) as total_products FROM gold.dim_products

-- find the total number of customers
SELECT COUNT(customer_key) as total_customers FROM gold.dim_customers

-- find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) as total_customers FROM gold.fact_sales

--Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' as measure_name ,
SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name ,
SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) From gold.fact_sales
UNION ALL
SELECT 'Total Nr.Orders', COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr.Products', COUNT(product_name)  FROM gold.dim_products
UNION ALL 
SELECT 'Total Nr.Customers', COUNT(customer_key)  FROM gold.dim_customers

--Magnitude Exploration
-- find total customers by countries
SELECT 
country, 
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- find total customers by gender
SELECT 
gender, 
COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- find total products by category
SELECT 
category, 
COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- what is the average costs in each category?
SELECT 
category, 
AVG(cost) as avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- what is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY  total_revenue DESC

-- find total revenue is generated by each custome
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- what is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

--Ranking Analysis
--which 5 products generate the highest revenue?
SELECT TOP 5 
p.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY  total_revenue DESC

--what are the 5 worst- performng products in terms of sales?
SELECT TOP 5 
p.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY  total_revenue 

--find the top 10 customers who have generated the highest revenue 
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

---- find the 3 customers with the fewest orders placed?
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) as total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders


